<!DOCTYPE html><html lang="pt" >

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  
  
  
    <meta name="generator" content="Wowchemy 5.0.0-beta.3 for Hugo" />
  

  

  
  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Mateus Cavalcanti Pestana" />

  
  
  
    
  
  <meta name="description" content="De Ícaro ao Tesla Roadster, voar sempre foi a vontade de muitos. Há quem diga que tem medo, e não duvido, embora acredite que o medo está não na altura ou no voar, mas nos possíveis acidentes que podem decorrer disso." />

  
  <link rel="alternate" hreflang="pt" href="https://mateuspestana.github.io/post/quem-voa/quem-voa-analise-dos-voos-da-fab-com-autoridades-do-estado/" />

  







  




  
  
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  

  
  
  
    <meta name="theme-color" content="#1565c0" />
  

  
  
    
    <script src="/js/mathjax-config.js"></script>
  

  
  
  
  
    
    
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.9.0/css/academicons.min.css" integrity="sha512-W4yqoT1+8NLkinBLBZko+dFB2ZbHsYLDdr50VElllRcNt2Q4/GSs6u71UHKxB7S6JEMCp5Ve4xjh3eGQl/HRvg==" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha256-FMvZuGapsJLjouA6k7Eo2lusoAX9i0ShlWFG6qt7SLc=" crossorigin="anonymous">

    
    

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/styles/github.min.css" crossorigin="anonymous" title="hl-light" media="print" onload="this.media='all'">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" media="print" onload="this.media='all'" disabled>
        
      
    

    
    
    
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.min.css" integrity="sha512-1xoFisiGdy9nvho8EgXuXvnpR5GAMSjFwp40gSRE3NwdUdIMIKuPa7bqoUhLD0O/5tPNhteAsE5XyyMi5reQVA==" crossorigin="anonymous" media="print" onload="this.media='all'">
    

    

    
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" integrity="" crossorigin="anonymous" async></script>
      
    
      
      

      
      

      
    
      
      

      
      

      
    
  

  
  
  
    
      
      <link rel="preload" as="style" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&family=Roboto+Mono&family=Roboto:wght@400;700&display=swap">
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&family=Roboto+Mono&family=Roboto:wght@400;700&display=swap" media="print" onload="this.media='all'">
    
  

  
  
  
  
  
  <link rel="stylesheet" href="/css/wowchemy.003d2be57501b5669ca58ef75468ece2.css" />

  




<script async src="https://www.googletagmanager.com/gtag/js?id=UA-150193464-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];

  function gtag() {
      dataLayer.push(arguments);
  }

  function trackOutboundLink(url, target) {
    gtag('event', 'click', {
         'event_category': 'outbound',
         'event_label': url,
         'transport_type': 'beacon',
         'event_callback': function () {
           if (target !== '_blank') {
             document.location = url;
           }
         }
    });
    console.debug("Outbound link clicked: " + url);
  }

  function onClickCallback(event) {
    if ((event.target.tagName !== 'A') || (event.target.host === window.location.host)) {
      return;
    }
    trackOutboundLink(event.target, event.target.getAttribute('target'));  
  }

  gtag('js', new Date());
  gtag('config', 'UA-150193464-1', {});
  gtag('set', {'cookie_flags': 'SameSite=None;Secure'});

  
  document.addEventListener('click', onClickCallback, false);
</script>


  

  

  




  
  
  

  

  
    <link rel="manifest" href="/index.webmanifest" />
  

  <link rel="icon" type="image/png" href="/media/icon_hua2ec155b4296a9c9791d015323e16eb5_11927_32x32_fill_lanczos_center_2.png" />
  <link rel="apple-touch-icon" type="image/png" href="/media/icon_hua2ec155b4296a9c9791d015323e16eb5_11927_180x180_fill_lanczos_center_2.png" />

  <link rel="canonical" href="https://mateuspestana.github.io/post/quem-voa/quem-voa-analise-dos-voos-da-fab-com-autoridades-do-estado/" />

  
  
  
  
  
  
  
  
    
    
  
  
  <meta property="twitter:card" content="summary" />
  
  <meta property="og:site_name" content="Mateus C. Pestana" />
  <meta property="og:url" content="https://mateuspestana.github.io/post/quem-voa/quem-voa-analise-dos-voos-da-fab-com-autoridades-do-estado/" />
  <meta property="og:title" content="Quem Voa - Análise dos vôos da FAB com autoridades do Estado | Mateus C. Pestana" />
  <meta property="og:description" content="De Ícaro ao Tesla Roadster, voar sempre foi a vontade de muitos. Há quem diga que tem medo, e não duvido, embora acredite que o medo está não na altura ou no voar, mas nos possíveis acidentes que podem decorrer disso." /><meta property="og:image" content="https://mateuspestana.github.io/media/icon_hua2ec155b4296a9c9791d015323e16eb5_11927_512x512_fill_lanczos_center_2.png" />
    <meta property="twitter:image" content="https://mateuspestana.github.io/media/icon_hua2ec155b4296a9c9791d015323e16eb5_11927_512x512_fill_lanczos_center_2.png" /><meta property="og:locale" content="pt" />
  
    
      <meta
        property="article:published_time"
        content="2019-10-16T00:00:00&#43;00:00"
      />
    
    <meta property="article:modified_time" content="2019-10-15T22:28:21-03:00">
  

  


    






  




<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://mateuspestana.github.io/post/quem-voa/quem-voa-analise-dos-voos-da-fab-com-autoridades-do-estado/"
  },
  "headline": "Quem Voa - Análise dos vôos da FAB com autoridades do Estado",
  
  "datePublished": "2019-10-16T00:00:00Z",
  "dateModified": "2019-10-15T22:28:21-03:00",
  
  "author": {
    "@type": "Person",
    "name": "Mateus Cavalcanti Pestana"
  },
  
  "publisher": {
    "@type": "Organization",
    "name": "Mateus C. Pestana",
    "logo": {
      "@type": "ImageObject",
      "url": "https://mateuspestana.github.io/media/icon_hua2ec155b4296a9c9791d015323e16eb5_11927_192x192_fill_lanczos_center_2.png"
    }
  },
  "description": "De Ícaro ao Tesla Roadster, voar sempre foi a vontade de muitos. Há quem diga que tem medo, e não duvido, embora acredite que o medo está não na altura ou no voar, mas nos possíveis acidentes que podem decorrer disso."
}
</script>

  

  

  

  <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
<script src="https://gist.githubusercontent.com/jeremyyeo/03930a03108330d5579fe88b79604c41/raw/2aa8e8a614dbc47c9af81156d0663d3e2e4bdfc6/htmlwidgets.js"></script>

  <title>Quem Voa - Análise dos vôos da FAB com autoridades do Estado | Mateus C. Pestana</title>
</head>


<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" class="page-wrapper   " data-wc-page-id="d03360dfdb0c0cdb0b731a218dbf0304" >

  
  
  
  
  
  
  
  
  <script src="/js/wowchemy-init.min.9f8405b7756f5e178a738a09c302f8b3.js"></script>

  


<aside class="search-modal" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Pesquisar</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#" aria-label="Close"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Pesquisar..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search" class="form-control"
        aria-label="Pesquisar...">
        
      </div>

      
      

      

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>



  <div class="page-header">
    












<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container-xl">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/">Mateus C. Pestana</a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar" aria-expanded="false" aria-label="Alterar navegação">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/">Mateus C. Pestana</a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-start" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
            
            
            
              
            
            
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#about"><span>Biografia</span></a>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
            
            
            
              
            
            
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#posts"><span>Posts</span></a>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
            
            
            
              
            
            
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#portfolio"><span>Portfolio</span></a>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
            
            
            
              
            
            
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#publications"><span>Publicações</span></a>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/cursos"><span>Cursos</span></a>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
            
            
            
              
            
            
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#contact"><span>Contato</span></a>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/media/resume.pdf"><span>Currículo</span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">

      
      
        
      

      
      
      <li class="nav-item">
        <a class="nav-link js-search" href="#" aria-label="Pesquisar"><i class="fas fa-search" aria-hidden="true"></i></a>
      </li>
      

      
      

      

    </ul>

  </div>
</nav>


  </div>

  <div class="page-body">
    <article class="article">

  












  

  
  
  
<div class="article-container pt-3">
  <h1>Quem Voa - Análise dos vôos da FAB com autoridades do Estado</h1>

  

  
    


<div class="article-metadata">

  
  
  
  
  <div>
    

  <span class="author-highlighted">
      <a href="/author/mateus-cavalcanti-pestana/">Mateus Cavalcanti Pestana</a></span>
  </div>
  
  

  
  <span class="article-date">
    
    
      
          Última atualização em
      
    
    15 de Oct, 2019
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    11 minutos de leitura
  </span>
  

  
  
  
  
  
  

  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fas fa-folder mr-1"></i><a href="/category/analise-exploratoria/">análise exploratória</a>, <a href="/category/ciencia-de-dados/">ciência de dados</a>, <a href="/category/ciencia-politica/">ciência política</a></span>
  

</div>

    





  
</div>



  <div class="article-container">

    <div class="article-style">
      
<script src="2019-10-15-quem-voa-análise-dos-vôos-da-fab-com-autoridades-do-estado_files/header-attrs/header-attrs.js"></script>
<script src="2019-10-15-quem-voa-análise-dos-vôos-da-fab-com-autoridades-do-estado_files/kePrint/kePrint.js"></script>
<link href="2019-10-15-quem-voa-análise-dos-vôos-da-fab-com-autoridades-do-estado_files/lightable/lightable.css" rel="stylesheet" />


<p>De Ícaro ao <a href="https://pt.wikipedia.org/wiki/Tesla_Roadster_de_Elon_Musk">Tesla Roadster</a>, voar sempre foi a vontade de muitos. Há quem diga que tem medo, e não duvido, embora acredite que o medo está não na altura ou no voar, mas nos possíveis acidentes que podem decorrer disso. De uma forma ou de outra, o céu brasileiro está cada vez mais povoado com a democratização do preço dos vôos, da quantidade de trechos disponíveis e da necessidade de chegar mais rápido em algum lugar.</p>
<p>Pensando nisso, e pesquisando os <a href="http://dados.gov.br/">dados abertos do governo brasileiro</a>, descobri um <a href="https://github.com/FABdadosabertos/GABAER">repositório da Força Aéreea Brasileira</a> com bancos de dados de todas as autoridades que voaram de abril de 2019 até setembro desse ano. A primeira vez que vi esses arquivos, no mês passado, eles iam somente até agosto, e hoje já temos o banco com os dados de setembro. Logo, espero que continuem fazendo a manutenção dos mesmos e continuem disponibilizando dados de interesse do cidadão.</p>
<p>Antigamente, os vôos da FAB ficavam disponíveis somente no site da mesma, <a href="http://www.fab.mil.br/voos">aqui</a>, e os dados não podiam ser exportados, pois vinham em formato PDF, separados por dia. Era possível raspar os PDFs, mas o trabalho seria um pouco custoso. De toda forma, agora, todos os vôos estão disponíveis em formato <strong>.csv</strong> e são de fácil acesso e processamento.</p>
<p>Como exercício, farei uma breve análise exploratória desses bancos, e me proponho a manter a análise atualizada conforme os próximos meses forem consolidados no arquivo.</p>
<p>Clonando o repositório em nossa máquina, é preciso listar todos os arquivos em .csv, para então formar o banco. Para acelerar esse processo, depois de carregar os pacotes que utilizarei, vou juntar todos os arquivos de uma vez e já direcionar ao banco, para não ter que importar um a um dentro do R.</p>
<pre class="r"><code>pacman::p_load(tidyverse, hrbrthemes, knitr, kableExtra, janitor, ggalt)

files &lt;- list.files(&quot;~/Documents/Datasets/QuemVoa/&quot;, pattern = &quot;.csv$&quot;, full.names = T)

names_vars &lt;- c(&quot;autoridade&quot;, &quot;origem&quot;, &quot;orig_data_hora&quot;,
                &quot;destino&quot;, &quot;dest_data_hora&quot;, &quot;motivo&quot;,
                &quot;n_pass&quot;, &quot;compartilhado&quot; )

fab &lt;- bind_rows(lapply(files, read.csv2, 
                        header = F, encoding = &quot;latin1&quot;, 
                        col.names = names_vars))</code></pre>
<p>Explicando o código acima: criei um objeto chamado <code>files</code> que listava todos os arquivos em <strong>.csv</strong> da pasta. O uso de <code>$</code>, em <code>regex</code>, significa “termina com”. No caso, tudo que termina com <strong>.csv</strong>, a extensão dos arquivos utilizados.</p>
<p>Em seguida, criei um vetor chamado <code>names_vars</code>. A explicação é que os arquivos da FAB não vem com os nomes da variáveis, logo, para facilitar nosso trabalho, criei um vetor nomes identificáveis que permitirão uma melhor compreensão e execução.</p>
<p>Já o objeto de nome <code>fab</code> é o banco em si, que, a partir da função <code>bind_rows</code> e um <code>lapply</code>, abre todos os arquivos da lista e direciona para o objeto, consolidando todos de uma só vez, na codificação correta (latin1) e com os nomes de variáveis anteriormente especificados.</p>
<p>Agora, vamos dar uma olhada no banco:</p>
<pre class="r"><code>glimpse(fab)</code></pre>
<pre><code>## Rows: 849
## Columns: 8
## $ autoridade     &lt;chr&gt; &quot;Presidente da Câmara dos Deputados&quot;, &quot;Presidente da Câ…
## $ origem         &lt;chr&gt; &quot;Brasília&quot;, &quot;Rio de Janeiro (Santos Dumont)&quot;, &quot;São Paul…
## $ orig_data_hora &lt;chr&gt; &quot;01/04/2019 - 07:10&quot;, &quot;01/04/2019 - 11:05&quot;, &quot;01/04/2019…
## $ destino        &lt;chr&gt; &quot;Rio de Janeiro (Santos Dumont)&quot;, &quot;São Paulo (Congonhas…
## $ dest_data_hora &lt;chr&gt; &quot;01/04/2019 - 08:40&quot;, &quot;01/04/2019 - 11:55&quot;, &quot;01/04/2019…
## $ motivo         &lt;chr&gt; &quot;Residência&quot;, &quot;Serviço&quot;, &quot;Residência&quot;, &quot;Serviço&quot;, &quot;Serv…
## $ n_pass         &lt;int&gt; 9, 9, 9, 9, 25, 12, 14, 14, 14, 14, 12, 5, 4, 14, 12, 1…
## $ compartilhado  &lt;chr&gt; &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;,…</code></pre>
<p>Temos 849 observações, ou vôos, com 8 variáveis, que vão desde a autoridade que utilizou a aeronave, passando pela origem e destino, o motivo, o número previsto de passageiros e se o vôo foi compartilhado ou não com outra autoridade. Como pode ser visto, esse banco não nos facilita muito em nossa análise, principalmente pelo fato do dia e da hora estarem em uma mesma variável. É importante separá-los ao máximo para que possamos tornar esse banco o mais <a href="https://garrettgman.github.io/tidying/"><code>tidy</code></a> possível.</p>
<pre class="r"><code>fab &lt;- fab %&gt;% 
  separate(orig_data_hora, c(&quot;orig_dia&quot;, &quot;orig_mes&quot;, &quot;orig_ano&quot;), sep = &quot;/&quot;) %&gt;% # Separando uma coluna em 3
  separate(dest_data_hora, c(&quot;dest_dia&quot;, &quot;dest_mes&quot;, &quot;dest_ano&quot;), sep = &quot;/&quot;) %&gt;% # Separando uma coluna em 3
  mutate(dest_ano = str_replace(dest_ano, &quot; - &quot;, &quot; &quot;), # Tirando o &quot; - &quot; que ficou na coluna
         orig_ano = str_replace(orig_ano, &quot; - &quot;, &quot; &quot;), # Tirando o &quot; - &quot; que ficou na coluna
         dest_ano = str_replace(dest_ano, &quot;: &quot;, &quot;:&quot;)) %&gt;% # Uma linha tinha um erro (um espaço depois de :)
  separate(dest_ano, c(&quot;dest_ano&quot;, &quot;dest_hora&quot;), sep = &quot; &quot;) %&gt;% # Separando em 2
  separate(orig_ano, c(&quot;orig_ano&quot;, &quot;orig_hora&quot;), sep = &quot; &quot;) %&gt;% # Separando em 2
  mutate_if(is.character, as.factor) # Strings como fatores

meses &lt;- c(&quot;Abril&quot;, &quot;Maio&quot;, &quot;Junho&quot;, &quot;Julho&quot;, &quot;Agosto&quot;, &quot;Setembro&quot;) # Salvando um vetor com os nomes dos meses


glimpse(fab)</code></pre>
<pre><code>## Rows: 849
## Columns: 14
## $ autoridade    &lt;fct&gt; &quot;Presidente da Câmara dos Deputados&quot;, &quot;Presidente da Câm…
## $ origem        &lt;fct&gt; Brasília, Rio de Janeiro (Santos Dumont), São Paulo (Con…
## $ orig_dia      &lt;fct&gt; 01, 01, 01, 01, 01, 02, 02, 02, 02, 02, 03, 03, 03, 04, …
## $ orig_mes      &lt;fct&gt; 04, 04, 04, 04, 04, 04, 04, 04, 04, 04, 04, 04, 04, 04, …
## $ orig_ano      &lt;fct&gt; 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 20…
## $ orig_hora     &lt;fct&gt; 07:10, 11:05, 17:25, 19:05, 14:35, 10:15, 08:10, 16:55, …
## $ destino       &lt;fct&gt; Rio de Janeiro (Santos Dumont), São Paulo (Congonhas), R…
## $ dest_dia      &lt;fct&gt; 01, 01, 01, 01, 01, 02, 02, 02, 02, 02, 03, 03, 03, 04, …
## $ dest_mes      &lt;fct&gt; 04, 04, 04, 04, 04, 04, 04, 04, 04, 04, 04, 04, 04, 04, …
## $ dest_ano      &lt;fct&gt; 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 20…
## $ dest_hora     &lt;fct&gt; 08:40, 11:55, 18:10, 20:35, 16:00, 11:35, 10:20, 19:20, …
## $ motivo        &lt;fct&gt; Residência, Serviço, Residência, Serviço, Serviço, Servi…
## $ n_pass        &lt;int&gt; 9, 9, 9, 9, 25, 12, 14, 14, 14, 14, 12, 5, 4, 14, 12, 14…
## $ compartilhado &lt;fct&gt; &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, …</code></pre>
<p>Pronto! Agora podemos iniciar a nossa análise.</p>
<pre class="r"><code># Quais as principais origens dos vôos?
fab %&gt;% 
  tabyl(origem) %&gt;% 
  top_n(n = 10) %&gt;% 
  ggplot()+
  geom_col(aes(x = reorder(origem, n), y = n),
           fill = &quot;#2d543d&quot;)+
  coord_flip()+
  labs(title = &quot;Top 10 origens de vôos da FAB&quot;,
       subtitle = &quot;Com autoridades do Estado&quot;,
       x = &quot;Cidade de Origem&quot;,
       y = &quot;Nº de Vôos&quot;,
       caption = &quot;Fonte: GABAER/FAB&quot;)+
  theme_ipsum_tw()</code></pre>
<p><img src="/post/quem-voa/2019-10-15-quem-voa-ana%CC%81lise-dos-vo%CC%82os-da-fab-com-autoridades-do-estado_files/figure-html/origens-1.png" width="672" /></p>
<pre class="r"><code># Qual o principal destino dos vôos?
fab %&gt;% 
  tabyl(destino) %&gt;% 
  top_n(n = 10) %&gt;% 
  ggplot()+
  geom_col(aes(x = reorder(destino, n), y = n),
           fill = &quot;#d175b8&quot;)+
  coord_flip()+
  labs(title = &quot;Top 10 destinos de vôos da FAB&quot;,
       subtitle = &quot;Com autoridades do Estado&quot;,
       x = &quot;Cidade de Destino&quot;,
       y = &quot;Nº de Vôos&quot;,
       caption = &quot;Fonte: GABAER/FAB&quot;)+
  theme_ipsum_tw()</code></pre>
<p><img src="/post/quem-voa/2019-10-15-quem-voa-ana%CC%81lise-dos-vo%CC%82os-da-fab-com-autoridades-do-estado_files/figure-html/origens-2.png" width="672" /></p>
<p>Ok, faz sentido que Brasília esteja no topo: as autoridades que podem utilizar os vôos da FAB trabalham majoritariamente lá. Vamos remove Brasília, então, para ver como as outras cidades se comportam.</p>
<pre class="r"><code># Principais origens (sem contar com BSB)
fab %&gt;% 
  filter(origem != &quot;Brasília&quot;) %&gt;% 
  tabyl(origem) %&gt;% 
  top_n(n = 10) %&gt;% 
  ggplot()+
  geom_col(aes(x = reorder(origem, n), y = n),
           fill = &quot;#2d543d&quot;)+
  coord_flip()+
  labs(title = &quot;Top 10 origem de vôos da FAB&quot;,
       subtitle = &quot;Com autoridades do Estado, sem vôos de Brasília&quot;,
       x = &quot;Cidade de Destino&quot;,
       y = &quot;Nº de Vôos&quot;,
       caption = &quot;Fonte: GABAER/FAB&quot;) +
  theme_ipsum_tw()</code></pre>
<p><img src="/post/quem-voa/2019-10-15-quem-voa-ana%CC%81lise-dos-vo%CC%82os-da-fab-com-autoridades-do-estado_files/figure-html/origens_nobsb-1.png" width="672" /></p>
<pre class="r"><code># Principais destinos (sem contar com BSB)
fab %&gt;% 
  filter(destino != &quot;Brasília&quot;) %&gt;% 
  tabyl(destino) %&gt;% 
  top_n(n = 10) %&gt;% 
  ggplot()+
  geom_col(aes(x = reorder(destino, n), y = n),
           fill = &quot;#d175b8&quot;)+
  coord_flip()+
  labs(title = &quot;Top 10 destinos de vôos da FAB&quot;,
       subtitle = &quot;Com autoridades do Estado, sem vôos para Brasília&quot;,
       x = &quot;Cidade de Destino&quot;,
       y = &quot;Nº de Vôos&quot;,
       caption = &quot;Fonte: GABAER/FAB&quot;) +
  theme_ipsum_tw()</code></pre>
<p><img src="/post/quem-voa/2019-10-15-quem-voa-ana%CC%81lise-dos-vo%CC%82os-da-fab-com-autoridades-do-estado_files/figure-html/origens_nobsb-2.png" width="672" /></p>
<p>Os aeroportos de Congonhas, em São Paulo, e o Santos Dumont, no Rio de Janeiro, lideram a lista de origens e destinos. Sabendo os lugares, podemos analisar agora o mês. Em qual mês houve uma quantidade superior de vôos?</p>
<pre class="r"><code>fab %&gt;% 
  tabyl(orig_mes) %&gt;% 
  ggplot()+
  geom_col(aes(x = orig_mes, y  = n, fill = orig_mes),
           show.legend = F)+
  labs(title = &quot;Nº de vôos por mês&quot;,
       subtitle = &quot;Com autoridades em aviões da FAB&quot;, 
       y = &quot;Qtde. de vôos&quot;,
       x = &quot;Mês&quot;,
       caption = &quot;Fonte: GABAER/FAB&quot;)+
  scale_x_discrete(labels = meses)+
  scale_fill_ipsum()+
  theme_ipsum_tw()</code></pre>
<p><img src="/post/quem-voa/2019-10-15-quem-voa-ana%CC%81lise-dos-vo%CC%82os-da-fab-com-autoridades-do-estado_files/figure-html/meses-1.png" width="672" /></p>
<pre class="r"><code>fab %&gt;% 
  tabyl(orig_mes) %&gt;% 
  select(orig_mes, n) %&gt;% 
  kable(col.names = c(&quot;Mês&quot;, &quot;Nº de vôos&quot;)) %&gt;% 
  kable_paper()</code></pre>
<table class=" lightable-paper" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Mês
</th>
<th style="text-align:right;">
Nº de vôos
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
04
</td>
<td style="text-align:right;">
134
</td>
</tr>
<tr>
<td style="text-align:left;">
05
</td>
<td style="text-align:right;">
139
</td>
</tr>
<tr>
<td style="text-align:left;">
06
</td>
<td style="text-align:right;">
127
</td>
</tr>
<tr>
<td style="text-align:left;">
07
</td>
<td style="text-align:right;">
118
</td>
</tr>
<tr>
<td style="text-align:left;">
08
</td>
<td style="text-align:right;">
177
</td>
</tr>
<tr>
<td style="text-align:left;">
09
</td>
<td style="text-align:right;">
154
</td>
</tr>
</tbody>
</table>
<p>O mês de agosto aparentemente foi atípico por algum motivo que desconhecemos: 177 vôos foram realizados. Como será que os vôos foram distribuídos ao longo do mês de agosto?</p>
<pre class="r"><code>fab %&gt;% 
  filter(orig_mes == &quot;08&quot;) %&gt;% 
  ggplot(aes(x = as.numeric(orig_dia)))+
  geom_density(fill = &quot;#2d543d&quot;, alpha = 0.75)+
  theme_ipsum_tw()+
  labs(title = &quot;Vôos de Agosto&quot;,
       subtitlee = &quot;Densidade da Distribuição&quot;,
       y = &quot;Densidade&quot;, 
       x = &quot;Dia do mês de Agosto&quot;,
       caption = &quot;Fonte: GABAER/FAB&quot;)+
  scale_x_continuous(breaks =  seq(1, 31, 3))</code></pre>
<p><img src="/post/quem-voa/2019-10-15-quem-voa-ana%CC%81lise-dos-vo%CC%82os-da-fab-com-autoridades-do-estado_files/figure-html/voos_agosto-1.png" width="672" /></p>
<p>É possível perceber que os vôos da FAB foram mais utilizados a partir do dia 20, dado que a curva da densidade é maior em tal recorte temporal. É preciso saber o que houve no final de agosto para entender o aumento no fluxo de vôos.</p>
<p>Continuando, agora é importante saber qual autoridade mais viajou. Como a lista é enorme, vamos verificar só os 9 maiores cargos, pela quantidade de vôos realizados e procurar algum padrão nesses dados:</p>
<pre class="r"><code>fab %&gt;% 
  tabyl(autoridade) %&gt;% 
  top_n(9) %&gt;% 
  ggplot()+
  geom_lollipop(aes(x = reorder(autoridade, n), y = n),
           show.legend = F, size = 1.2, color = &quot;#8fd175&quot;)+
  coord_flip()+
  scale_color_ipsum()+
  labs(title = &quot;Quem viaja mais?&quot;,
       x = &quot;&quot;,
       y = &quot;Qtde. de vôos&quot;,
       caption = &quot;Fonte: GABAER/FAB&quot;)+
  theme_ipsum_tw()</code></pre>
<pre><code>## Selecting by percent</code></pre>
<p><img src="/post/quem-voa/2019-10-15-quem-voa-ana%CC%81lise-dos-vo%CC%82os-da-fab-com-autoridades-do-estado_files/figure-html/voos_auths-1.png" width="672" /></p>
<p>A partir do gráfico acima, podemos perceber que Rodrigo Maia (DEM) é a autoridade que mais viaja em vôos da FAB, na figura de Presidente da Câmara dos Deputados do Brasil.</p>
<pre class="r"><code>fab %&gt;% 
  filter(autoridade == &quot;Presidente da Câmara dos Deputados&quot;) %&gt;% 
  tabyl(origem) %&gt;% 
  filter(n &gt;= 1) %&gt;% 
  arrange(-n) %&gt;% 
  head(15) %&gt;% 
  ggplot(aes(x = reorder(origem, n), y  = n))+
  geom_lollipop(size = 1.3, color = &quot;steelblue&quot;)+
  coord_flip()+
  theme_ipsum_tw()+
  labs(title  = &quot;Vôos de Rodrigo Maia&quot;,
       x = &quot;&quot;,
       y = &quot;Qtde. de Vôos&quot;,
       caption  = &quot;Fonte: GABAER/FAB&quot;)</code></pre>
<p><img src="/post/quem-voa/2019-10-15-quem-voa-ana%CC%81lise-dos-vo%CC%82os-da-fab-com-autoridades-do-estado_files/figure-html/voos_rodmaia-1.png" width="672" /></p>
<p>Acima, é notável que Brasília é o principal destino de Rodrigo Maia entre abril e setembro de 2019, e o aeroporto de Congonhas é o segundo destino. Isso seria de se estranhar, dado o fato de que Rodrigo Maia mora no Rio de Janeiro, estado pelo qual é deputado. Entretanto, se somarmos os dois aeroportos do Rio (Santos Dumont e Galeão), percebemos que o número de saídas do Rio é superior ao número de saídas de São Paulo: enquanto 27 vôos são originados em São Paulo (Congonhas + Guarulhos), do Rio, se somarmos os dois aeroportos, teremos 28 vôos.</p>
<pre class="r"><code>fab %&gt;% 
  filter(autoridade == &quot;Presidente da Câmara dos Deputados&quot;) %&gt;% 
  tabyl(origem) %&gt;% 
  arrange(-n) %&gt;% 
  head(5) %&gt;% 
  select(origem, n) %&gt;% 
  kable(col.names = c(&quot;Origem&quot;,  &quot;Nº de vôos&quot;)) %&gt;% 
  kable_paper()</code></pre>
<table class=" lightable-paper" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Origem
</th>
<th style="text-align:right;">
Nº de vôos
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Brasília
</td>
<td style="text-align:right;">
50
</td>
</tr>
<tr>
<td style="text-align:left;">
São Paulo (Congonhas)
</td>
<td style="text-align:right;">
24
</td>
</tr>
<tr>
<td style="text-align:left;">
Rio de Janeiro (Santos Dumont)
</td>
<td style="text-align:right;">
22
</td>
</tr>
<tr>
<td style="text-align:left;">
Rio de Janeiro (Galeão)
</td>
<td style="text-align:right;">
6
</td>
</tr>
<tr>
<td style="text-align:left;">
Guarulhos
</td>
<td style="text-align:right;">
3
</td>
</tr>
</tbody>
</table>
<p>Uma outra variável oferecida no banco da FAB é a variável denominada <code>motivo</code>, onde estão listados o que as autoridades que voaram alegaram como motivação para tal.</p>
<pre class="r"><code>fab %&gt;% 
   mutate(motivo = ifelse(motivo == &quot;Segurança/Serviço&quot;, &quot;Serviço/Segurança&quot;, 
                          as.character(motivo)),
          motivo = ifelse(motivo == &quot;Serviço/Serviço&quot;, &quot;Serviço&quot;, as.character(motivo)),
          motivo = ifelse(motivo == &quot;Serviço/ Segurança&quot;, &quot;Serviço/Segurança&quot;, as.character(motivo))) %&gt;% 
  tabyl(motivo) %&gt;% 
  ggplot(aes(x = reorder(motivo, -n), y  = n))+
  geom_col(fill = &quot;#c9d175&quot;)+
  #coord_flip()+
  geom_label(aes(label  = n), vjust = -0.1, size = 3.5)+
  theme_ipsum_tw()+
  labs(title  = &quot;Motivos de viagem&quot;,
       subtitle  = &quot;Segundo autoridades em vôos da FAB&quot;,
       x = &quot;Motivo&quot;,
       y = &quot;Nº de vôos&quot;,
       caption = &quot;Fonte: GABAER/FAB&quot;)+
  ylim(0, 800)</code></pre>
<p><img src="/post/quem-voa/2019-10-15-quem-voa-ana%CC%81lise-dos-vo%CC%82os-da-fab-com-autoridades-do-estado_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Como podemos ver, poucos vôos são efetivamente para a residência da autoridade, e a maioria é em serviço, cerca de 740 vôos até então. Percebemos que existiu uma emergência médica, uma de segurança e 26 casos de residência. Vamos analisar:</p>
<pre class="r"><code>fab %&gt;% 
  filter(motivo == &quot;Emergência Médica&quot; | motivo == &quot;Segurança&quot;) %&gt;% 
  select(autoridade, orig_dia, orig_mes, origem, destino, motivo) %&gt;% 
  kable(col.names = c(&quot;Autoridade&quot;, &quot;Dia&quot;, &quot;Mês&quot;, &quot;Origem&quot;, &quot;Destino&quot;, &quot;Motivo&quot;)) %&gt;% kable_paper()</code></pre>
<table class=" lightable-paper" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Autoridade
</th>
<th style="text-align:left;">
Dia
</th>
<th style="text-align:left;">
Mês
</th>
<th style="text-align:left;">
Origem
</th>
<th style="text-align:left;">
Destino
</th>
<th style="text-align:left;">
Motivo
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Ministro do Meio Ambiente
</td>
<td style="text-align:left;">
28
</td>
<td style="text-align:left;">
08
</td>
<td style="text-align:left;">
Brasília
</td>
<td style="text-align:left;">
São Paulo (Congonhas)
</td>
<td style="text-align:left;">
Emergência Médica
</td>
</tr>
<tr>
<td style="text-align:left;">
Ministro da Economia
</td>
<td style="text-align:left;">
09
</td>
<td style="text-align:left;">
09
</td>
<td style="text-align:left;">
Rio de Janeiro (Santos Dumont)
</td>
<td style="text-align:left;">
Brasília
</td>
<td style="text-align:left;">
Segurança
</td>
</tr>
</tbody>
</table>
<p>Ou seja, Ricardo Salles sofreu uma emergência médica (e ficou hospitalizado), enquanto Paulo Guedes, por motivos de segurança, no dia 09/09/2019, foi do Rio até Brasília.</p>
<p>E quem usa os vôos da FAB para ir para casa? O presidente da Câmara dos Deputados, Rodrigo Maia:</p>
<pre class="r"><code>fab %&gt;% 
  mutate(autoridade = as.character(autoridade)) %&gt;% 
  filter(motivo == &quot;Residência&quot;) %&gt;% 
  tabyl(autoridade) %&gt;% 
  select(autoridade, n) %&gt;% 
  kable(col.names = c(&quot;Autoridade&quot;, &quot;Nº de vôos para casa&quot;)) %&gt;% 
  kable_styling(bootstrap_options = c(&quot;hover&quot;, &quot;condensed&quot;))</code></pre>
<table class="table table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Autoridade
</th>
<th style="text-align:right;">
Nº de vôos para casa
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Presidente da Câmara dos Deputados
</td>
<td style="text-align:right;">
26
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>fab %&gt;% 
  filter(autoridade == &quot;Presidente da Câmara dos Deputados&quot;,
         motivo == &quot;Residência&quot;) %&gt;% 
  ggplot(aes(x = orig_mes, y = orig_dia, color = origem))+
  geom_point(size = 2)+
  theme_ipsum_tw()+
  theme(legend.position = &quot;bottom&quot;)+
  labs(title = &quot;Quando Rodrigo Maia foi pra casa&quot;,
       subtitle  = &quot;Dia e mês de cada vôo do deputado com motivo residencial&quot;,
       x = &quot;Mês&quot;,
       y  = &quot;Dia&quot;, 
       color = &quot;Origem&quot;,
       caption = &quot;Fonte: GABAER/FAB&quot;)+
  scale_color_ipsum()+
  scale_x_discrete(labels = meses)</code></pre>
<p><img src="/post/quem-voa/2019-10-15-quem-voa-ana%CC%81lise-dos-vo%CC%82os-da-fab-com-autoridades-do-estado_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Bom, por hoje é só! Enquanto o banco de dados da FAB for disponibilizado e atualizado, manterei esse arquivo em dia. A principal dica é: acessem o portal de <a href="dados.gov.br">Dados Abertos do Brasil</a> e analisem as informações lá disponibilizadas.</p>
<p>Qualquer dúvida, correção ou sugestão pode ser encaminhada para <a href="mailto:matheus.pestana@iesp.uerj.br" class="email">matheus.pestana@iesp.uerj.br</a></p>

    </div>

    






<div class="article-tags">
  
  <a class="badge badge-light" href="/tag/r/">r</a>
  
  <a class="badge badge-light" href="/tag/opendata/">opendata</a>
  
  <a class="badge badge-light" href="/tag/brasil/">brasil</a>
  
  <a class="badge badge-light" href="/tag/governo/">governo</a>
  
</div>



<div class="share-box" aria-hidden="true">
  <ul class="share">
    
      
      
      
        
      
      
      
      <li>
        <a href="https://twitter.com/intent/tweet?url=https://mateuspestana.github.io/post/quem-voa/quem-voa-analise-dos-voos-da-fab-com-autoridades-do-estado/&amp;text=Quem%20Voa%20-%20An%c3%a1lise%20dos%20v%c3%b4os%20da%20FAB%20com%20autoridades%20do%20Estado" target="_blank" rel="noopener" class="share-btn-twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.facebook.com/sharer.php?u=https://mateuspestana.github.io/post/quem-voa/quem-voa-analise-dos-voos-da-fab-com-autoridades-do-estado/&amp;t=Quem%20Voa%20-%20An%c3%a1lise%20dos%20v%c3%b4os%20da%20FAB%20com%20autoridades%20do%20Estado" target="_blank" rel="noopener" class="share-btn-facebook">
          <i class="fab fa-facebook"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="mailto:?subject=Quem%20Voa%20-%20An%c3%a1lise%20dos%20v%c3%b4os%20da%20FAB%20com%20autoridades%20do%20Estado&amp;body=https://mateuspestana.github.io/post/quem-voa/quem-voa-analise-dos-voos-da-fab-com-autoridades-do-estado/" target="_blank" rel="noopener" class="share-btn-email">
          <i class="fas fa-envelope"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.linkedin.com/shareArticle?url=https://mateuspestana.github.io/post/quem-voa/quem-voa-analise-dos-voos-da-fab-com-autoridades-do-estado/&amp;title=Quem%20Voa%20-%20An%c3%a1lise%20dos%20v%c3%b4os%20da%20FAB%20com%20autoridades%20do%20Estado" target="_blank" rel="noopener" class="share-btn-linkedin">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="whatsapp://send?text=Quem%20Voa%20-%20An%c3%a1lise%20dos%20v%c3%b4os%20da%20FAB%20com%20autoridades%20do%20Estado%20https://mateuspestana.github.io/post/quem-voa/quem-voa-analise-dos-voos-da-fab-com-autoridades-do-estado/" target="_blank" rel="noopener" class="share-btn-whatsapp">
          <i class="fab fa-whatsapp"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://service.weibo.com/share/share.php?url=https://mateuspestana.github.io/post/quem-voa/quem-voa-analise-dos-voos-da-fab-com-autoridades-do-estado/&amp;title=Quem%20Voa%20-%20An%c3%a1lise%20dos%20v%c3%b4os%20da%20FAB%20com%20autoridades%20do%20Estado" target="_blank" rel="noopener" class="share-btn-weibo">
          <i class="fab fa-weibo"></i>
        </a>
      </li>
    
  </ul>
</div>











  
  
    



  
  
  
    
  
  
  
  <div class="media author-card content-widget-hr">
    
      
      <a href="https://mateuspestana.github.io"><img class="avatar mr-3 avatar-circle" src="/author/mateus-cavalcanti-pestana/avatar_hufeccfd6f9380df9b18ea9dcb1ceea097_79518_270x270_fill_q75_lanczos_center.jpg" alt="Mateus Cavalcanti Pestana"></a>
    

    <div class="media-body">
      <h5 class="card-title"><a href="https://mateuspestana.github.io">Mateus Cavalcanti Pestana</a></h5>
      <h6 class="card-subtitle">Doutorando e Mestre em Ciência Política</h6>
      <p class="card-text">Interessado em ciência de dados, ciência política, política russa, impressão 3D, redes neurais e aprendizado de máquina.</p>
      <ul class="network-icon" aria-hidden="true">
  
    
    
    
      
    
    
    
    
    
    <li>
      <a href="mailto:matheus.pestana@iesp.uerj.br" >
        <i class="fas fa-envelope"></i>
      </a>
    </li>
  
    
    
    
    
    
    
    
      
    
    <li>
      <a href="http://lattes.cnpq.br/0027872463024148" target="_blank" rel="noopener">
        <i class="ai ai-lattes"></i>
      </a>
    </li>
  
    
    
    
    
    
    
    
      
    
    <li>
      <a href="https://scholar.google.com.br/citations?user=jpRDWpgAAAAJ&amp;hl=pt-BR" target="_blank" rel="noopener">
        <i class="ai ai-google-scholar"></i>
      </a>
    </li>
  
    
    
    
    
    
    
    
      
    
    <li>
      <a href="https://orcid.org/0000-0002-5388-8950" target="_blank" rel="noopener">
        <i class="ai ai-orcid"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://github.com/mateuspestana" target="_blank" rel="noopener">
        <i class="fab fa-github"></i>
      </a>
    </li>
  
    
    
    
    
    
    
    
      
    
    <li>
      <a href="/media/resume.pdf" >
        <i class="ai ai-cv"></i>
      </a>
    </li>
  
</ul>

    </div>
  </div>


  














  
  
  <div class="article-widget content-widget-hr">
    <h3>Relacionados</h3>
    <ul>
      
      <li><a href="/post/textmining-getulio-vargas/textmining-analise-dos-discursos-de-getulio-vargas/">Textmining: análise dos discursos de Getúlio Vargas</a></li>
      
      <li><a href="/portfolio/2021-03-02-votaai/">VotaAí</a></li>
      
      <li><a href="/post/decision-trees/decision-trees-no-r-analise-do-enem-2018/">Decision Trees no R: Análise do ENEM 2018</a></li>
      
      <li><a href="/portfolio/2021-03-02-candidaturas-religiosas/">Candidaturas Religiosas</a></li>
      
      <li><a href="/post/imprimindo_graficos/imprimindo-graficos-em-3d-no-r/">Imprimindo gráficos em 3D no R</a></li>
      
    </ul>
  </div>
  





  </div>
</article>
  </div>

  <div class="page-footer">
    
    
    <div class="container">
      <footer class="site-footer">
  

  <p class="powered-by">
    © 2021 Matheus C. Pestana
  </p>

  
  






  <p class="powered-by">
    
    
    
      
      
      
      
      
      
      Published with <a href="https://wowchemy.com/?utm_campaign=poweredby" target="_blank" rel="noopener">Wowchemy</a> — the free, <a href="https://github.com/wowchemy/wowchemy-hugo-modules" target="_blank" rel="noopener">open source</a> website builder that empowers creators.
    
  </p>
</footer>

    </div>
    
  </div>

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Citação</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copiar
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

      

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/instant.page/5.1.0/instantpage.min.js" integrity="sha512-1+qUtKoh9XZW7j+6LhRMAyOrgSQKenQ4mluTR+cvxXjP1Z54RxZuzstR/H9kgPXQsVB8IW7DMDFUJpzLjvhGSQ==" crossorigin="anonymous"></script>

      
      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      

      
      

      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.8.4/mermaid.min.js" integrity="sha512-as1BF4+iHZ3BVO6LLDQ7zrbvTXM+c/1iZ1qII/c3c4L8Rn5tHLpFUtpaEtBNS92f+xGsCzsD7b62XP3XYap6oA==" crossorigin="anonymous" title="mermaid"></script>
      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/highlight.min.js" integrity="sha512-TDKKr+IvoqZnPzc3l35hdjpHD0m+b2EC2SrLEgKDRWpxf2rFCxemkgvJ5kfU48ip+Y+m2XVKyOCD85ybtlZDmw==" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/languages/r.min.js"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/languages/python.min.js"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/languages/latex.min.js"></script>
        
      

    

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.min.js" integrity="sha512-SeiQaaDh73yrb56sTW/RgVdi/mMqNeM2oBwubFHagc5BkixSpP1fvqF47mKzPGWYSSy4RwbBunrJBQ4Co8fRWA==" crossorigin="anonymous"></script>
    

    
    

    
    
    
      
      <script id="search-hit-fuse-template" type="text/x-template">
        <div class="search-hit" id="summary-{{key}}">
          <div class="search-hit-content">
            <div class="search-hit-name">
              <a href="{{relpermalink}}">{{title}}</a>
              <div class="article-metadata search-hit-type">{{type}}</div>
              <p class="search-hit-description">{{snippet}}</p>
            </div>
          </div>
        </div>
      </script>
      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
      
    

    
    

    
    
    
    

    <script src="/js/_vendor/bootstrap.bundle.min.f81d0a1705048649befc8b595e455a94.js"></script>

    
    
      
      
      
      
      
      
      
    

    
    
    
    
    
    
    
    
      
      
    
    
    <script src="/pt/js/wowchemy.min.e74a71a7cfab89f71b427a2bd20b61f8.js"></script>

    
  <script async defer src="https://buttons.github.io/buttons.js"></script>




</body>
</html>
